### ISSUE TITLE
Getting content for our Medium publication

### ISSUE THREAD

**Issue by OpesanyaAdebayo** [nodejsnigeria/ecosystem#9]
While we are planning to open NodeSchool chapters, I think we can put out a call to the ecosystem to encourage content generation. Also, it will help us maintain our Twitter presence.
So people submit articles, and if we review and decide that it is fit to be published, then we do so. For the ones that are published, we can generate a score based on number of views, reads and claps. This can run for a month and then we select three winners at the end of the month.
These winners are then announced on Twitter.
What do you think?

**Comment by pmbanugo** [comment]
I guess I oppose a lot of things lol. I don't like the idea of making winners. I want we focus on content generation

**Comment by OpesanyaAdebayo** [comment]
Well, maybe "winners" doesn't best communicate the right spirit, but I don't think there's any problem doing things like "Our Top 3 Articles For The Month are..." for the following reasons:

- As much as we want people to do things with pure motives, it's also encouraging to provide reward systems for those who do a good job. It's actually something I would put on my CV if my articles made the list, so intrinsically, we have provided value to them in their search for opportunity. Who knows who will see it an be impressed?
- Also, it gives us some PR strength because people whose articles make the list will share on Twitter
- At some point, we'll start sending newsletters, and we're going to do it anyway

**Comment by pmbanugo** [comment]
Then I like the idea as you described now    On Friday, October 12, 2018, 3:41:31 AM GMT+1, onejsninja <notifications@github.com> wrote:  
 
 
Well, maybe "winners" doesn't best communicate the right spirit, but I don't think there's any problem doing things like "Our Top 3 Articles For The Month are..." for the following reasons:
   
   - As much as we want people to do things with pure motives, it's also encouraging to provide reward systems for those who do a good job. It's actually something I would put on my CV if my articles made the list, so intrinsically, we have provided value to them in their search for opportunity. Who knows who will see it an be impressed?
   - Also, it gives us some PR strength because people whose articles make the list will share on Twitter
   - At some point, we'll start sending newsletters, and we're going to do it anyway

**Comment by segunadeleye** [comment]
I like the idea of 'Top Articles'. The word 'winners' makes it feel like a competition and that's not what we want.

**Comment by OpesanyaAdebayo** [comment]
Awesome! I'll work on my language next time.

So when should we make the announcement, and how?

I'm thinking there should be a blog post, so it's detailed enough and we can share that on Twitter as well. I can draw up a draft for us to review.
I think we can make the announcement on Sunday or Monday.

**Comment by OpesanyaAdebayo** [comment]
Closing this issue since we already made the announcement [here](https://medium.com/node-nigeria-blog/announcing-node-js-nigeria-blog-7a31b2588cb5)
